name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Push images to GitHub Container Registry
      run:
        docker login -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build -t ghcr.io/harshitkh1/backend:latest ./backend
        docker build -t ghcr.io/harshitkh1/frontend:latest ./frontend
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u harshitkh1 --password-stdin
        docker push ghcr.io/harshitkh1/backend:latest
        docker push ghcr.io/harshitkh1/frontend:latest
